[package]
name = "wasm-emoji"
version = "0.1.0"
authors = ["steven.roulleau <steven.roulleau@myscript.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.71"
